name: Continue Intergration and Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Install dependencies
        run: dotnet restore "TEST-CICD/test-ci-cd/Test-CI-CD.sln"

      - name: Build app
        run: dotnet build "TEST-CICD/test-ci-cd/Test-CI-CD.sln"
